- Monitoring:
    - Uptime Kuma:
        icon: uptime-kuma
        href: https://status.{{HOMEPAGE_VAR_DOMAIN}}
        description: Monitoring & Alerts
        widget:
          type: uptimekuma
          url: http://uptime-kuma:3001
          slug: uptime

- Home Server:
    - Homepage:
        icon: homepage
        href: https://home.{{HOMEPAGE_VAR_DOMAIN}}
        description: Dashboard
    - Caddy:
        icon: caddy
        href: http://localhost:80
        description: Reverse Proxy
        siteMonitor: http://caddy-proxy:80
    - Nextcloud:
        icon: nextcloud
        href: https://nextcloud.{{HOMEPAGE_VAR_DOMAIN}}
        description: Cloud Storage & Sync
        siteMonitor: https://nextcloud.{{HOMEPAGE_VAR_DOMAIN}}
    - Vaultwarden:
        icon: vaultwarden
        href: https://vaultwarden.{{HOMEPAGE_VAR_DOMAIN}}
        description: Password Manager
        siteMonitor: http://vaultwarden:80
    - Immich:
        icon: immich
        href: https://immich.{{HOMEPAGE_VAR_DOMAIN}}
        description: Photo & Video Backup
        siteMonitor: http://immich-server:2283
        widget:
          type: immich
          url: http://immich-server:2283
          key: '{{HOMEPAGE_VAR_IMMICH_API_KEY}}'
          version: 2
    - Ring Intercom:
        icon: mdi-doorbell
        href: https://ring.{{HOMEPAGE_VAR_DOMAIN}}
        description: Ring Intercom Server
        siteMonitor: http://ring-server:3000
